insta_001/Controllers/InstController.cs
using insta_001.Models;
using insta_001.Parser;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace insta_001.Controllers
{
    public class InstController : Controller
    {
        // GET: Inst
        public ActionResult Index(bool isMyAcc = false)
        {
            InstParser p = new InstParser();
            List<InstModel> comms = new List<InstModel>();

            if (isMyAcc == true)
            {
                comms = p.Main(true);
            }
            else
            {
                comms = p.Main();
            }

            if (comms != null)
            {
                comms = SortByCommCreated(comms);
                ViewBag.AllPosts = comms.Count;
                comms = comms.GetRange(0, 30);
                return PartialView("Index", comms);
            }

            else return PartialView(new List<InstModel>());
        }
        [HttpPost]
        public ActionResult AjaxSortByPostCreated(List<InstModel> comms = null)
        {
            var val2 = Request.UrlReferrer.Query;

            InstParser p = new InstParser();
            comms = new List<InstModel>();

            if (val2 == "?isMyAcc=True")
            {
                comms = p.Main(true);
            }
            else
            {
                comms = p.Main();
            }
            if (comms != null)
            {
                comms = comms.Where(ev => ev.comments.Count() > 0).OrderByDescending(ev => ev.created).ToList();
            }
            ViewBag.AllPosts = comms.Count;
            comms = comms.GetRange(0, 30);
            return PartialView("AjaxUpdate", comms);
        }

       
        public ActionResult AjaxSortByCommCreated(List<InstModel> comms = null)
        {
            var val2 = Request.UrlReferrer.Query;

            InstParser p = new InstParser();
            comms = new List<InstModel>();

            if (val2 == "?isMyAcc=True")
            {
                comms = p.Main(true);
            }
            else
            {
                comms = p.Main();
            }
            comms = SortByCommCreated(comms);
            ViewBag.AllPosts = comms.Count;
            comms = comms.GetRange(0, 30);

            return PartialView("AjaxUpdate", comms);
        }

        [HttpPost]
        public ActionResult GetInstDataJson(InstModel model)
        {
            return Json(model);
            // return Json(new { success = true });
        }


        public List<InstModel> SortByCommCreated(List<InstModel> comms)
        {
            //comms = comms.Where(ev => ev.comments.Count > 0).ToList();
            for (int i = 0; i < comms.Count(); i++)
            {
                for (int j = 0; j < comms.Count() - i - 1; j++)
                {
                    if (comms[j].comments.Last().created < comms[j + 1].comments.Last().created)
                    {
                        var temp = comms[j];
                        comms[j] = comms[j + 1];
                        comms[j + 1] = temp;
                    }
                }
            }
            return comms;
        }
    }
}

insta_001/Controllers/VkController.cs
using insta_001.Models;
using insta_001.Parser;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace insta_001.Controllers
{
    public class VkController : Controller
    {
        // GET: Vk
        public ActionResult Index()
        {
            VkParser v = new VkParser();
            List<VkModel> vk = v.Main();
            vk = vk.OrderByDescending(ev => ev.created).ToList();
            return View(vk);
        }
    }
}

insta_001/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Insta Check</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link rel="icon" type="image/png" href="~/Files/favicon.png">
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/ajax")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <!--   <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                      <span class="icon-bar"></span>
                      <span class="icon-bar"></span>
                      <span class="icon-bar"></span>
                  </button> -->
             
                @Html.ActionLink("home", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                @Html.ActionLink("myInst", "Index", "Inst", new { isMyAcc = true }, new { @class = "navbar-brand" })
                @Html.ActionLink("inst", "Index", "Inst", new { area = "" }, new { @class = "navbar-brand" })
                @Html.ActionLink("vk", "Index", "Vk", new { area = "" }, new { @class = "navbar-brand" })
            </div>

            <!--
                <div class="navbar-collapse collapse">
                  <ul class="nav navbar-nav">
                  </ul>
              </div>
            -->
        </div>
    </div>

    <div class="container body-content" style="padding:0px;">
        @RenderBody()
        <hr />
        <footer></footer>
    </div>
    <script src="~/Scripts/bootstrap.min.js"></script>

</body>
</html>